name: CI-OC-2

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: fabricioH2/devops-pipelines/.github/workflows/main.yml@main
    with:
      docker_image_name: hola-mundo-clase123
    secrets: inherit