name: CI-OC-2

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: FabricioH2/devops-pipelines/.github/workflows/docker-workflow.yml@main
    with:
      docker_image_name: fabricioph2/micro-2
    secrets: inherit